version: '3'
services:
  database:
    container_name: testProject_db
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      .env
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - db
  backend:
    container_name: testProject_backend
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      .env
    depends_on: 
      - database
    networks:
      - db
volumes:
  db-data:
networks:
  db:
    driver: bridge